#!/bin/bash
# Step-by-step interactive Hugging Face deployment

echo "🔐 Hugging Face Authentication & Deployment Guide"
echo "=================================================="
echo ""
echo "Step 1: Get your Hugging Face Token"
echo "   1. Go to: https://huggingface.co/settings/tokens"
echo "   2. Click 'New token'"
echo "   3. Name it: 'misinformation-deploy'"
echo "   4. Type: Write"
echo "   5. Copy the token"
echo ""
echo "Step 2: Login to Hugging Face"
echo "   Run this command and paste your token when prompted:"
echo ""
echo "   source /home/ndii/Documents/Mark/model-playground/venv/bin/activate"
echo "   huggingface-cli login"
echo ""
echo "Step 3: Deploy the model"
echo "   cd /home/ndii/Documents/Mark/model-playground/api/ml_service"
echo "   ./deploy_to_hf.sh"
echo ""
echo "=================================================="
